import {
  Activity,
  ArrowLeftRight,
  ArrowRight,
  Building2,
  CalendarCheck,
  CalendarDays,
  CarFront,
  CirclePlus,
  ClipboardCheck,
  ClipboardList,
  CreditCard,
  DollarSign,
  FileText,
  GraduationCap,
  LayoutDashboard,
  Map,
  MapPinned,
  MoreHorizontal,
  BookOpen,
  Settings,
  ShieldBan,
  ShieldCheck,
  Star,
  User,
  UserRoundCog,
  UserPlus,
  Users,
  BadgeCheck,
  Briefcase,
  Wrench,
} from "lucide-react";

export const dashboardIcons = {
  users: Users,
  schools: Building2,
  learners: GraduationCap,
  revenue: DollarSign,

  activity: Activity,
  userPlus: UserPlus,
  creditCard: CreditCard,
  shieldCheck: ShieldCheck,
  shieldBan: ShieldBan,

  add: CirclePlus,
  report: FileText,
  manageUsers: Users,
  verify: ShieldCheck,
  building: Building2,
  arrowRight: ArrowRight,
  transfer: ArrowLeftRight,
  more: MoreHorizontal,
  calendar: CalendarDays,
  clipboard: ClipboardList,
  clipboardCheck: ClipboardCheck,
  car: CarFront,
  dashboard: LayoutDashboard,
  settings: Settings,
  user: User,

  // ===== Owner Portal =====

  school: Building2,
  branches: MapPinned,

  instructor: UserRoundCog,
  instructors: UserRoundCog,

  course: BookOpen,
  booking: CalendarCheck,
  schedule: CalendarDays,
  attendance: ClipboardCheck,
  payment: CreditCard,
  subscription: CreditCard,
  maintenance: Wrench,
  review: Star,
  star: Star,

  map: Map,
  certificate: BadgeCheck,

  active: Briefcase,
} as const;

export type DashboardIcon = keyof typeof dashboardIcons;
