import {
  LayoutDashboard,
  Users,
  GraduationCap,
  MapPinned,
  Map,
  FileText,
  CreditCard,
  Headset,
  Settings,
  CalendarDays,
  ClipboardList,
  User,
  CalendarCheck,
  Bell,
  Car,
  UserRoundCog,
  Building2,
  BookOpen,
  Star,
} from "lucide-react";

export const sidebarIcons = {
  "layout-dashboard": LayoutDashboard,
  users: Users,
  "graduation-cap": GraduationCap,
  map: Map,
  "map-pinned": MapPinned,
  "file-text": FileText,
  "credit-card": CreditCard,
  headset: Headset,
  settings: Settings,
  "calendar-days": CalendarDays,
  "clipboard-list": ClipboardList,
  user: User,
  "calendar-check": CalendarCheck,
  bell: Bell,
  car: Car,
  "user-round-cog": UserRoundCog,
  school: Building2,
  "book-open": BookOpen,
  star: Star,
} as const;
